### ISSUE TITLE
The project is running fine on the local host , but after deploying on Heroku it showing the same error .  Error ( AttributeError: 'OneHotEncoder' object has no attribute '_infrequent_enabled' )

### ISSUE THREAD

**Issue by AshutoshDubey88** [Kartiksood10/Laptop-Price-Predictor#1]
please help me in that issue
![Uploading Screenshot (4).png…]()

**Comment by AshutoshDubey88** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/85121661/197358419-aa0f8877-3917-4828-b2ec-17a7d05da49c.png)

**Comment by Kartiksood10** [comment]
Hey @AshutoshDubey88,
The error is coming while using python 3.9 and 3.10.
So here is the fix:

1. Download and install python 3.7.9 from python.org(download executable installer)
2. Make sure you repair it during installation
3. Change python interpreter on pycharm to 3.7.9(you will have to restart pycharm for the new interpreter to show)
4. You will have to create a new project with the new python interpreter.
5. Make sure to add the runtime.txt file that I have on my GitHub-repo in pycharm.
6. Your code should now work.

**Comment by AshutoshDubey88** [comment]
but 3.7.9 version not available on Heroku deploy.
![Screenshot (7)](https://user-images.githubusercontent.com/85121661/197869554-47ad2270-7cc0-4112-8289-8650f3812b9b.png)

**Comment by Kartiksood10** [comment]
@AshutoshDubey88 I deployed mine on Heroku using python 3.7.9 (You can check out the link on my GitHub). Heroku by default runs the latest python while deploying so I suggest you add the runtime.txt file which I have used to force Heroku to apply 3.7.9 during deployment.
